http:
  routers:
    backend:
      rule: "Host(`backend.localhost`)"
      service: backend
      entryPoints:
        - securedocker-compose up --build -d

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:3000"