entryPoints:
  web:
    address: ":80"
  secure:
    address: ":8443"

providers:
  file:
    filename: "/etc/traefik/dynamic_conf.yml"
    watch: true

tls:
  certificates:
    - certFile: "/certs/selfsigned.crt"
      keyFile: "/certs/selfsigned.key"
